server:
   port: 8060
 #  servlet:
  #    context-path: /mall-order
#spring.cloud.nacos.config.group=mall
spring:
   application:
      name: mall-order
   cloud:
      nacos:
         discovery:
            server-addr: 192.168.4.160:8848
#spring.cloud.nacos.config.file-extension=properties
   datasource:
      driver-class-name: oracle.jdbc.OracleDriver
      url: jdbc:oracle:thin:@192.168.4.160:1521:orcl
      username: scott
      password: 1
      ConnectionTestQuery: select 1 from dual
   #zipkin: 
      #base-url: http://192.168.4.160:7700
   #sleuth: 
      #sampler: 
         #percentage: 1.0
   kafka: 
      bootstrap-servers: 192.168.7.148:9092
      producer: 
         key-serializer: org.apache.kafka.common.serialization.StringSerializer
         value-serializer: org.apache.kafka.common.serialization.StringSerializer
      consumer:
         #group-id: default_consumer_group #群组ID
         enable-auto-commit: true
         auto-commit-interval: 1000
         key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
         value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
mybatis:
   mapper-locations: classpath:mapper/*Mapper.xml

#=====feign相关配置===============================
feign:
  hystrix:
    enabled: true  #feign开启hystrix
  okhttp:
    enabled: true #feign使用okhttp提高性能
  compression:
    request:
      enabled: true #request and response GZIP compress
      mime-types: text/xml,application/xml,application/json #compress supportive mime types
      min-request-size: 2048
    response:
      enabled: true
ribbon:
  ConnectTimeout: 1000 # 设置连接超时时间 1秒
  ReadTimeout: 10000    # 设置读取超时时间 6秒
  OkToRetryOnAllOperations: false  # 对所有操作请求都进行重试
  MaxAutoRetriesNextServer: 2   # 切换实例的重试次数
  MaxAutoRetries: 1  # 对当前实例的重试次数
  eager-load:
    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 40000  # 设置熔断超时时间10s
#========================================


management:
  endpoints:
    health: 
      show-details: always
    web:
      exposure:
        include: "*"


swagger:
  enable: true

#logging:
   #config: classpath:logback-spring.xml
